### ISSUE TITLE
ts2phc configuration file should include pin_index

### ISSUE THREAD

**Issue by 652436962** [jclark/pc-ptp-ntp-guide#1]
Why don’t you need to specify sdp?

 cat /etc/linuxptp/ts2phc-generic.cfg

[global]
ts2phc.extts_polarity both
ts2phc.pulsewidth 100000000
leapfile /usr/share/zoneinfo/leap-seconds.list
step_threshold 0.1

ts2phc.nmea_serialport /dev/ttyS9

ts2phc.nmea_baudrate 9600

logging_level 7

[enp1s0]

**Comment by 652436962** [comment]
cat /etc/linuxptp/ts2phc-generic.cfg
# Configuration file for ts2phc
# For more information about this file, see the ts2phc(8) man page.
[global]
ts2phc.extts_polarity both
ts2phc.pulsewidth 100000000
leapfile /usr/share/zoneinfo/leap-seconds.list
step_threshold 0.1

# these are only used with -s nmea, and are ignored with -s generic
ts2phc.nmea_serialport /dev/ttyS9
# This is only supported with Linux PTP 4.x
ts2phc.nmea_baudrate 9600

# In LinuxPTP 3.x, you need logging_level to be 7 in order to get messages showing the PPS-PHC offsets.
# With LinuxPTP 4.x, you get these messages at log level 6 (which is the default).
logging_level 7

[enp1s0]

**Comment by jclark** [comment]
You mean `ts2phc.pin_index`, right?  It defaults to zero, which is often right, but I agree it would be helpful to put it in the configuration file. Thanks for the suggestion!

**Comment by 652436962** [comment]
”> You mean `ts2phc.pin_index`, right? It defaults to zero, which is often right, but I agree it would be helpful to put it in the configuration file. Thanks for the suggestion!”
 You mean `ts2phc.pin_index`, right?   yes
I started the task based on your documentation and official documentation, but after a while there will be a value of a few microseconds. Is this normal?

![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/bca108f4-360f-4ed8-a289-850be2bcd425)
![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/a08ca30c-55c5-4bd8-9de9-64c1d1517d65)

![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/7775c125-814a-4e08-a877-5ee6bff9ed51)

**Comment by jclark** [comment]
Is there a switch between the GM and the client?

**Comment by 652436962** [comment]
> Is there a switch between the GM and the client?

no

**Comment by jclark** [comment]
That doesn't sound normal.

- What is your hardware configuration (GM, client, GPS)?
- What are you measuring? What is showing a value of a few microseconds?

I don't understand what ts2phc_slave is doing,

**Comment by 652436962** [comment]
> That doesn't sound normal.
> 
> * What is your hardware configuration (GM, client, GPS)?
> * What are you measuring? What is showing a value of a few microseconds?
> 
> I don't understand what ts2phc_slave is doing,

os : buildroot

gm is  rockchip3568   inter i210    gprmc + pps  .   


ts2phc_slave  output  1pps


between  gm 1pps  and ptp client have  a value of a few microseconds

**Comment by jclark** [comment]
Sorry, I don't understand. Please explain your setup in much more detail.

I still don't understand why you are using ts2phc_slave. Why aren't you getting the PPS from the GM using PHC periodic output on the SDP of the i210?

**Comment by 652436962** [comment]
> Sorry, I don't understand. Please explain your setup in much more detail.
> 
> I still don't understand why you are using ts2phc_slave. Why aren't you getting the PPS from the GM using PHC periodic output on the SDP of the i210?

The two devices are synchronized using ptp, and the slave device outputs 1pps through ts2phc

**Comment by jclark** [comment]
I am not going to be able to help unless you give me much, more detail.

- config files
- command lines
- logs
- hardware used for the client 
- hardware used for the GM in detail; I don't know what "rockchip3568 inter i210 gprmc + pps" means

**Comment by 652436962** [comment]
> I am not going to be able to help unless you give me much, more detail.
> 
> * config files
> * command lines
> * logs
> * hardware used for the client
> * hardware used for the GM in detail; I don't know what "rockchip3568 inter i210 gprmc + pps" means

Why aren't you getting the PPS from the GM using PHC periodic output on the SDP of the i210?
How to set this up specifically?

arm64   chip ： rk3568

ts2phc_slave 
[global]
use_syslog              0
verbose                 1
logging_level           6
ts2phc.pulsewidth       100000000
[enp1s0]
ts2phc.channel          0

ts2phc.extts_polarity   both
ts2phc.pin_index        1

**Comment by jclark** [comment]
You set it up like this:

https://github.com/jclark/rpi-cm4-ptp-guide/blob/main/measure.md#enable-pps-output

However with the i210, you cannot specify the `-w` argument. It always defaults to 50% duty cycle.

**Comment by 652436962** [comment]
> You set it up like this:
> 
> https://github.com/jclark/rpi-cm4-ptp-guide/blob/main/measure.md#enable-pps-output
> 
> However with the i210, you cannot specify the `-w` argument. It always defaults to 50% duty cycle.

I tested it, testptp cannot output on my platform

**Comment by jclark** [comment]
You're saying:

1. you have an i210
2. you have SDPs
3. external timestamping works
4. periodic output doesn't work

That seems very strange. I can't think of any reason why that could be the case.

What does `phc_ctl enp1s0` say?

**Comment by 652436962** [comment]
> You're saying:
> 
> 1. you have an i210
> 2. you have SDPs
> 3. external timestamping works
> 4. periodic output doesn't work
> 
> That seems very strange. I can't think of any reason why that could be the case.
> 
> What does `phc_ctl enp1s0` say?

I think it's a switch problem. I removed the switch and it doesn't seem to have this problem. I still need to test it.

**Comment by 652436962** [comment]
![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/7cf72436-0b3b-4c3f-bc26-609c41f23048)
![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/a4829f72-03a5-47a3-848f-3305fc5fda83)

I tested and found that after about 26393 seconds, the difference between the pps of his server and the client became larger and larger.

**Comment by jclark** [comment]
What happens after that?

My guess is that ts2phc got confused: it's not very robust. I suggest you start to investigate the problem by looking at the logs for ts2phc.

**Comment by 652436962** [comment]
> What happens after that?
> 
> My guess is that ts2phc got confused: it's not very robust. I suggest you start to investigate the problem by looking at the logs for ts2phc.

![image](https://github.com/jclark/pc-ptp-ntp-guide/assets/34038936/0f6c02c7-4cdc-47e5-988a-f0a645366120)
It shows this, there is no pps deviation data anymore

**Comment by jclark** [comment]
"poll returns zero" means that ts2phc isn't receiving PPS events.

"clearing Tx timestamp bug" suggests you have a kernel/driver problem (I guess a problem with igb driver on your ARM system).

**Comment by jclark** [comment]
What kernel are you using? Is the i210 on a separate PCIe card or is it on the board?

**Comment by 652436962** [comment]
> What kernel are you using? Is the i210 on a separate PCIe card or is it on the board?

 kernel 5.10     pcie2.0    rockchip rk3568（arm64）

**Comment by jclark** [comment]
This isn't going to be straightforward to fix.

I suggest first trying a newer kernel. I believe 6.1 is available or coming soon for the rk3568.  Another thing to try is to figure out whether this a arm64 problem or whether it's specific to rk3568.

 What board do you have?

**Comment by 652436962** [comment]
> This isn't going to be straightforward to fix.
> 
> I suggest first trying a newer kernel. I believe 6.1 is available or coming soon for the rk3568. Another thing to try is to figure out whether this a arm64 problem or whether it's specific to rk3568.
> 
> What board do you have?

itop-3568, a board by a small company

**Comment by 652436962** [comment]
ts2phc[481.201]: config item (null).free_running is 0
ts2phc[481.201]: PPS sink enp1s0 has ptp index 0
ts2phc[481.201]: UTC-TAI offset not set in system! Trying to revert to leapfile
ts2phc[481.201]: config item (null).leapfile is '/usr/share/zoneinfo/leap-seconds.list'
ts2phc[481.823]: UTC time is past leap second table expiry date
ts2phc[481.823]: source ts not valid
ts2phc[481.823]: UTC time is past leap second table expiry date
ts2phc[481.823]: source ts not valid
ts2phc[481.923]: UTC time is past leap second table expiry date
ts2phc[481.923]: source ts not valid
ts2phc[481.923]: UTC time is past leap second table expiry date
ts2phc[481.923]: source ts not valid
ts2phc[482.823]: UTC time is past leap second table expiry date
ts2phc[482.823]: source ts not valid
ts2phc[482.824]: UTC time is past leap second table expiry datets2phc[481.201]: config item (null).free_running is 0
ts2phc[481.201]: PPS sink enp1s0 has ptp index 0
ts2phc[481.201]: UTC-TAI offset not set in system! Trying to revert to leapfile
ts2phc[481.201]: config item (null).leapfile is '/usr/share/zoneinfo/leap-seconds.list'
ts2phc[481.823]: UTC time is past leap second table expiry date
ts2phc[481.823]: source ts not valid
ts2phc[481.823]: UTC time is past leap second table expiry date
ts2phc[481.823]: source ts not valid
ts2phc[481.923]: UTC time is past leap second table expiry date
ts2phc[481.923]: source ts not valid
ts2phc[481.923]: UTC time is past leap second table expiry date
ts2phc[481.923]: source ts not valid
ts2phc[482.823]: UTC time is past leap second table expiry date
ts2phc[482.823]: source ts not valid
ts2phc[482.824]: UTC time is past leap second table expiry date


hello ,  why is that?  I ran ts2phc according to the previous settings, and this appeared:

**Comment by jclark** [comment]
This means `/usr/share/zoneinfo/leap-seconds.list` is out of date. You can update the relevant distro package. Or download an updated one from 

https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list

**Comment by 652436962** [comment]
> This means is out of date. You can update the relevant distro package. Or download an updated one from`/usr/share/zoneinfo/leap-seconds.list`
> 
> https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list

ok thanks

**Comment by 652436962** [comment]
> This means is out of date. You can update the relevant distro package. Or download an updated one from`/usr/share/zoneinfo/leap-seconds.list`
> 
> https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list

In which directory are the logs generated by ts2phc located? Can I set the path?

**Comment by jclark** [comment]
ts2phc logs using syslog.

**Comment by 652436962** [comment]
> ts2phc logs using syslog.

thank  you
