### ISSUE TITLE
LinuxPTP as a grandmaster - typo?

### ISSUE THREAD

**Issue by KrzysztofKovic** [jclark/pc-ptp-ntp-guide#2]
Following your LinuxPTP as a grandmaster and I got stumped as to why the phc2sys service wasn't starting. 

1. Should say phc2sys.service  (And in your manifest the file goes into the phc.service directory.)
2. Should say phc2sys.sysconfig

![PTP GM](https://github.com/jclark/pc-ptp-ntp-guide/assets/157934413/ffc34c2f-bd3b-4d3b-bc0e-356f008be909)

**Comment by jclark** [comment]
Thanks.  I think I've fixed it now. Please check.

**Comment by KrzysztofKovic** [comment]
Looks good, thanks.

I've been searching for an answer regarding ethtool to no avail, so may I
ask one little question:

When I run ethtool -T enp3s0 I get hardware/software TX/RX as well as ptpv1
and ptpv2 filters modes - *all in a left column*.

When I see other web examples of timestamping NIC's it shows a bunch of SOF
options *in a right column*. Since I'm not getting that, does that just
mean I don't have the right NIC driver compiled? Can I go on to creating a
grandmaster without the SOF?

That's it. Not going to bombard you with questions.


Best,
Chris

**Comment by jclark** [comment]
With an Intel NIC, the output I get looks like:

```
Time stamping parameters for enp1s0:
Capabilities:
        hardware-transmit
        software-transmit
        hardware-receive
        software-receive
        software-system-clock
        hardware-raw-clock
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
        off
        on
Hardware Receive Filter Modes:
        none
        all
```

What output do you get?
What is your hardware and distro?
What is SOF?

More important for a GM is the presence of external time stamp channels, which you can see with `phc_ctl enp3s0`. You should see something like:

```
capabilities:
  62499999 maximum frequency adjustment (ppb)
  0 programable alarms
  2 external time stamp channels
  2 programmable periodic signals
  4 configurable input/output pins
  has pulse per second support
  doesn't have cross timestamping support
  doesn't have adjust phase support
```

**Comment by KrzysztofKovic** [comment]
Using a Tangent
<https://www.tangent.com/industrial-Pcs/rugged-mini-pc/rugged-q2/> mini PC
(1.83Ghz Celeron) with 2x Intel 82583V
<https://ark.intel.com/content/www/us/en/ark/products/41676/intel-82583v-gigabit-ethernet-controller.html>
NICS which support 1588.
Debian 12 netinstall.

My card:
***@***.***:~# ethtool -T enp3s0
Time stamping parameters for enp3s0:
Capabilities:
hardware-transmit
software-transmit
hardware-receive
software-receive
software-system-clock
hardware-raw-clock
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
off
on
Hardware Receive Filter Modes:
none
all
ptpv1-l4-sync
ptpv1-l4-delay-req
ptpv2-l4-sync
ptpv2-l4-delay-req
ptpv2-l2-sync
ptpv2-l2-delay-req
ptpv2-event
ptpv2-sync
ptpv2-delay-req

***@***.***:~# phc_ctl enp3s0
phc_ctl[98232.015]: cannot open /dev/ptp0 for enp3s0: Device or resource
busy


What I've been seeing a lot of as I'm reading about PTP:
[image: image.png]

This is a personal project and I'm not sure if I need not be led astray by
the "SOF" in question. I basically need the GM clocks to sync uncompressed,
multichannel audio over WAN. Since I had some seemingly capable hardware
laying around I figured why not try it out. Already configured are serial
GPS, gpsd, and chrony. Now that I think about it, I may use NTP instead
since PTP v2 will primarily be needed for networked audio hardware
<https://www.audinate.com/meet-dante/what-is-dante>.

**Comment by jclark** [comment]
To run a grandmaster it is not sufficient that your NIC supports IEEE 1588: it also needs to have a PPS input pin with driver support for external timestamping.  I believe the  82583V uses the e1000e driver which does not support external timestamping.

**Comment by KrzysztofKovic** [comment]
I really appreciate the clarification. So it seems the Beaglebone Black and
perhaps some software compiling should set me on the right path. Would you
agree?

**Comment by jclark** [comment]
Why do you think the Beaglebone Black will work?

The only low cost options I am aware of are the i210-T1 and a Raspberry Pi CM4.

**Comment by jclark** [comment]
Just to be clear: the PPS pin needs to be connected to the NIC so that input pulses are timestamped by the NIC hardware.

**Comment by KrzysztofKovic** [comment]
Primarily this:
https://usermanual.wiki/Document/SetupGuide.632280828.pdf

And this gentleman's reply here:
https://github.com/ptpd/ptpd/issues/72

**Comment by jclark** [comment]
There's two kinds of hardware timestamping that an ethernet controller can provide: timestamping the network packets (very common) and timestamping the pulses on a separate software-defined pin (not common).  The Linux kernel has support for both of these via the PTP hardware clock infrastructure. This guide requires hardware that is supported by the kernel for both of these.

The ptpd patches are only dealing with the hardware timestamping of network pulses.

I may be misunderstanding, but I think the guide you mentioned is about generating a PPS signal (so e.g. you can measure how accurately a client is synchronized to a grandmaster) not about using a PPS input to synchronize the PTP clock to a GPS.

I found the following threads

https://sourceforge.net/p/linuxptp/mailman/linuxptp-devel/thread/06829d9f-05ca-f66b-da22-157364755f63%40ti.com/
https://sourceforge.net/p/linuxptp/mailman/linuxptp-devel/thread/20200417043009.14819-1-lokeshvutla%40ti.com/

And this repo has a fork of LinuxPTP

https://git.ti.com/cgit/processor-sdk/linuxptp/tree/?h=ti-linuxptp

If your goal is to get a PTP grandmaster running, I suggest you follow the guides I've written either using an i210 (this repo) or a [Raspberry Pi CM4](https://github.com/jclark/rpi-cm4-ptp-guide).

**Comment by KrzysztofKovic** [comment]
James, thanks for all of your insight and time putting this information together. I learned a lot and I’ll probably take the i210 route. On Feb 5, 2024, at 8:35 PM, James Clark ***@***.***> wrote:﻿
There's two kinds of hardware timestamping that an ethernet controller can provide: timestamping the network packets (very common) and timestamping the pulses on a separate software-defined pin (not common).  The Linux kernel has support for both of these via the PTP hardware clock infrastructure. This guide requires hardware that is supported by the kernel for both of these.
The ptpd patches are only dealing with the hardware timestamping of network pulses.
I may be misunderstanding, but I think the guide you mentioned is about generating a PPS signal (so e.g. you can measure how accurately a client is synchronized to a grandmaster) not about using a PPS input to synchronize the PTP clock to a GPS.
I found the following threads
https://sourceforge.net/p/linuxptp/mailman/linuxptp-devel/thread/06829d9f-05ca-f66b-da22-157364755f63%40ti.com/
https://sourceforge.net/p/linuxptp/mailman/linuxptp-devel/thread/20200417043009.14819-1-lokeshvutla%40ti.com/
And this repo has a fork of LinuxPTP
https://git.ti.com/cgit/processor-sdk/linuxptp/tree/?h=ti-linuxptp
If your goal is to get a PTP grandmaster running, I suggest you follow the guides I've written either using an i210 (this repo) or a Raspberry Pi CM4.

**Comment by KrzysztofKovic** [comment]
Hi James,

I wound up getting a Intel i225-T1

Can you tell me if I hook up the GPS pps to SDP1 as shown here?  Reason I'm
weary of SDP0 is because mere observation of the board's front and back
show no indication of SDP0 going anywhere.

Timebeats illustration of the i226-T1
[image: Intel-i225-T1.jpg]

**Comment by jclark** [comment]
I use SDP1 regularly. SDP0 works too.  Did you buy the TimeBeat one with a presoldered header or are you soldering on a header yourself?

**Comment by jclark** [comment]
If you have a new question please open a new issue. Otherwise, it's easy to miss.
